server:
  port: 8080

spring:
  application:
    name: SmartAttendanceSystem

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/smartAttendanceSystem_DB?createDatabaseIfNotExist=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  threads:
    virtual:
      enabled: true

jwt:
  secret: ${JWT_SECRET:EfsSasSuperSecretKeyForIgnouProjectDoNotShare}
  expiration: 36000000